# Plain text secret for SOPS encryption
# Encrypt with: sops -e -i secret-app.yaml
# Decrypt with: sops -d secret-app.yaml
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: argocd-example-app
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:q+wnWFiXUoCkKT5G4jwqczYDPdQTQEYWQKQ=,iv:3MB6G3G3jfR/kiTLHvPBjg9F7mY4Tuq4D5jCJxiq7Ns=,tag:0ZnR7EL2m5wqLLr8WczjDQ==,type:str]
sops:
    age:
        - recipient: age1dvf63gewxhnydzt4yjlpp23qplqekt979udv4xgk47zct48kh40srrdjwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZDRKSk1IN2tDNGxQMTNm
            OC9hanpBV0ZYS3loTDVsVTdqNzhSU1ZWSENFCmJHdDF2MmFvMmE5OHBOVmcrR205
            eHVsR0VnY1Rzam9LMkdheHVUOVlhK00KLS0tIGFYeFVhWWZFeVdhT296NDdzY2xo
            TG9xWW45Qjk2UGlVZ2plclozUGJaV0EKqbh/vj9SibW0MLn5EARX9Tzzpxt/+lp9
            a4bVyle2PTijyFZn/qg8nSrXP1XPpGJkWoKMaJfwQDMQ7BzVz0LX7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T12:28:20Z"
    mac: ENC[AES256_GCM,data:+dUwz+eM7khJmBaQnsw96N/n0E4x3kl4SUlAA0XtG2UN0DjIDUl0Ud5Z6oUPs52Ihoj0Wu6veaU2wS5yEGDaCgfgXLNK216e0332LoGE34JWNHbccnYo+YWu+U78ZH+F3HUOywJxZAqUxxmHTpp+1qYfNSdOvAUVH112D2X6jSY=,iv:F+YN/5YmFfnHpMpDNuwvE+9ODCI2OiU/hD+uZD6OK9k=,tag:uC45srusk74BwxJpYgLaYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
