# Plain text secret for SOPS encryption
# Encrypt with: sops -e -i secret-app2.yaml
# Decrypt with: sops -d secret-app2.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app2-secret
  namespace: argocd-test-app2
type: Opaque
stringData:
  redis-password: ENC[AES256_GCM,data:Bl7V+U/FZQiCuVdK+utRu8vmS5926bXkT87bRQ==,iv:J0W/bDwrpPRQ8tP7eozT8t0yIjjPLva4R1e0CW4GTT8=,tag:bT00wW3Dg78/89BmRP7THw==,type:str]
sops:
  age:
    - recipient: age1dvf63gewxhnydzt4yjlpp23qplqekt979udv4xgk47zct48kh40srrdjwn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRGs1MnNjQ1d5OS9ucHVh
        TlkrbTRsbFdSYm9GWm01YVVETVg1a0hZWkhzCmhwQitWS0NQemx1M0FNcS84Z3ZZ
        WENQZTVGVHlSb09qSlZCSDdERG4zTWsKLS0tIGp5NEo3ZnJiem1UT2svMllhQzR5
        L05hZmNiVXlseGlPajZpU0FPYXVZcG8KhkFnOc1vbif8vKOhNQ5lv0FK6fA+5GjO
        1gC3IQP552wH82hCiefp/VrD3JBktmUpcEvvmX1R1IXLRFV1OQGC1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T17:32:14Z"
  mac: ENC[AES256_GCM,data:EdHFCDRzCWVCIXMeDMM0FgIAMKaGI/hNmp9oT8FebWiKIO07DbXPE0/ei6SXG3vdHn+AcgjdPifQ0wqf43ZibhRhq9j+ZLQSoKk2RNdzKqdG9DR8A87ihpCmrG77o3NZkhWjfTIrRL0fZHLCV9omCb0ZxS7yp+L6qUC6W6jy8Ec=,iv:YMeZGZFb2lZgYTmoxGTEXK1mMRlWIosSfQh8wWhvHfo=,tag:raL6WaYKuSoxnIHBAbL8yQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
