#ENC[AES256_GCM,data:w1YOx2UZ/WmM9bjv67VbzJ3aEGmujB8hACPsGi/988foT97/0MUXSwYYbOv7rYwwedqa+WjHnUHvjLtf,iv:CeWSK7R+Sf4z9ot1C9O7KQBFGh34RhQvPIhrxMFBq2Y=,tag:dQCuFIoTRcKsd5o7bt/2Nw==,type:comment]
#ENC[AES256_GCM,data:Y9s0V6oge3rHWOCGaGHPdyXWpMqa/IWlmfIWlBco4XhtUSn+t337R2t+G9MtugQCCCsqWg==,iv:Gl8/GzRKTCtrUEDjpeYKeOyGjR9lMLioR4fHLiL1X0s=,tag:uYnLLAFgXLNzgJ5p+1tRyw==,type:comment]
#
#ENC[AES256_GCM,data:yh/wHLFQnfXA0hmLuR6RfUyptRXUBpg6JraOCUoyV5irwb2dU7xWdPsvtC68qMXlP8/WbpPhfU8=,iv:CVWGb9Edt94UcHWfuZ2qZM1FKyuvzL3mcoJlsLZ7U/k=,tag:eUqhs0ow19lWZEJMNnNmbg==,type:comment]
#ENC[AES256_GCM,data:Wx0MQV9dsDc80nnsVs+TKek4UdOEmRJOtasnlzeKX2449Qvu+BRQU7B9IyTZ312ZGoX6jwfocv++Y4NVI2jeSWQSJ5LUbvclyQ8=,iv:qghaHDm7PAJ7ZL7w4LO0ryaZ7+zi/x+7adVapRSC3OQ=,tag:UBBsO51DgwzHldcfyiV56g==,type:comment]
services:
    cloudflared:
        networks:
            cloudflared: null
            alloy:
                ipv4_address: ENC[AES256_GCM,data:3UaKtEh08Ius0z0=,iv:RoTsbGeCSQDVZ7Nm4rEl7nEX+4Kigw59J7H+gRWNH+s=,tag:HaWDllTqcXRP4WthSt7e6g==,type:str]
            immich: null
            gitea: null
            vaultwarden: null
            code-server: null
networks:
    alloy:
        external: ENC[AES256_GCM,data:1OtOhw==,iv:jSsNcBjdXzZ/Tr3BHfIxvD9lhpSyNftkoLtIjOyvlaQ=,tag:heLDoPrhwVuU3fdtvAs2kA==,type:bool]
        name: ENC[AES256_GCM,data:0t/70LJwc+NKlqdsxF4=,iv:3E2lLSEeiNeDm4lNyCcaLe0iT4F1ZoS2lafCeddxrCk=,tag:9QdxI/ZoehHFL9SeVjiqag==,type:str]
    immich:
        external: ENC[AES256_GCM,data:UBCDqg==,iv:vlEA4Bhcy2YC/eAOzhEjBPlq+fIvMB8QSKqIu/XuIFM=,tag:K3VxG2yrO3JBS2JiYJZZXQ==,type:bool]
        name: ENC[AES256_GCM,data:aKODTmOou9Iv9BcN+ae8,iv:L92fBdZdxcrPmKSETdyFROT1y25hDrXLeYWXFXhcGjk=,tag:Iy/+Zrz+uBR/dppdMpMghQ==,type:str]
    gitea:
        external: ENC[AES256_GCM,data:CiojoQ==,iv:sgRUGqzeK7UMB29FO2ilcTQM4XyG8cst5jHNLeJA7Dg=,tag:txwiJRooZ9CGY5PRDcJr7Q==,type:bool]
        name: ENC[AES256_GCM,data:jciNhc7v7xHCY1QHPFo=,iv:yQNUzh2earvGFQsfjmXIVwo5C/luS9cRDtUXSuWhhh8=,tag:y/Nmsi6eWR7UiI2bFEO7zw==,type:str]
    vaultwarden:
        external: ENC[AES256_GCM,data:PNyjtw==,iv:ALYh3g5XpSV1MnfXk2cFIZcwL8r0vdMsmmEFOYHbVoI=,tag:e4pTlqG8ylFkeDo1Cc1GEw==,type:bool]
        name: ENC[AES256_GCM,data:drqC6RJpWcrPTvkwpUbHMzgVCaQ=,iv:Y+rdZ6i9TWm5uKeYPhx2djNS1tKCE8ajlD7Fqm/rjp8=,tag:7KeebcIVGwnfsDRhKZbcqA==,type:str]
    code-server:
        external: ENC[AES256_GCM,data:Aaz+0A==,iv:edvToYfeJbvB+tEy5VhPcHPE6Xt2bBV4NQoWuhIQ6iU=,tag:L2u5lRYSN8qYW0LujU1zig==,type:bool]
        name: ENC[AES256_GCM,data:sSdCfu0R2Pp7ToYtmIVol/DbjHI=,iv:NkOysbvckr8rIpCKO7QtrvEaUe+ptxGiHy7nhxQE6kY=,tag:7iKdwitfkbhTtc6FOxVEzA==,type:str]
sops:
    age:
        - recipient: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M2FZMm5JYythY1MzOW45
            b0FjOEVFcHA3aFhOaGRMSkNvMDhQZ3ZINWdvCitpNmJyZ0wyL0FCQUt2QzJjVXdS
            WmtrdlIxQTEzUXBGWHAra01UMG9QdncKLS0tIDlNOU5zZ3VjaXFNZDJJZEJ6STFE
            eHA5SktlRUxVQlBZNlVXeTdQNmxIcHMKc+/Qpz4it/u+3y21ZBXnBq5wn1ADO4D5
            n3e5tQTVOTOTbi9OVca8fPR6sGTPZJ6oZDuQ4oOiMAZXxUeHri70bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T05:26:12Z"
    mac: ENC[AES256_GCM,data:5XJ6FRXXzcN46cTt4y9v3vfqEcc+3/8xfCWjzQ9FVgE4xUtNJH7BXCRDbLgKN67qc1jX0cGBrTF6UyJaJUXQmOiebcsSlSvJpYO4og6OK1haA0axbJjd3998IbXcP2+iviG67tkCwFddLA9IuRIldAcqK/MDN/IWm2tOXJ6W6A8=,iv:lHQvgUyVcO5wB2PmuWrQSDwnq388BAlUiNqHyGwld5E=,tag:8MS6MCfnUcLT4JeezqEJHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
