# Plain text secret for SOPS encryption
# IMPORTANT: Replace placeholders with actual GitHub credentials
# Encrypt with: sops -e -i secret-ghcr-pull.yaml
# Decrypt with: sops -d secret-ghcr-pull.yaml
#
# To generate base64 auth string:
# echo -n "USERNAME:TOKEN" | base64
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: edatw-salary-mailman
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:73nqa9Z3mAksxjdu2DdcCYCYLQK6dwH+yqHRlTF92Sb0dy1UYjG8S+QpKWce82vyrHR9lmUxhHs/aVaSKkGzG/CASbWaNJyCshFfmMAVng0c31bUYfWTYq+ZBI5y0ubl9yaOGKdfZrM/OO63fSBLR//aDY10eZRRGEkyid9QmomtSa0d5a+oz34YipclF7Eacw==,iv:3dpzP3YXIMZN5ZgMf4xt26B8c/+JvDEj4lU7o44Rd4c=,tag:KW8Ve2n+ynZmDvFQVY+Zhg==,type:str]
sops:
  age:
    - recipient: age1dvf63gewxhnydzt4yjlpp23qplqekt979udv4xgk47zct48kh40srrdjwn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT3ZyNHRLY1c3SGxhZHhN
        MUlYOEI1YTVkcmdEak50Uzkvc2lSZXBZVHpBCjZ5L3g1RHVIbkZpSWZGaGhHb1lv
        Qzlod3dPVFUzNFR2N3h0dVhRSTJDS3cKLS0tIGwyUm9iaWw2Y3pkV3VJQkFpMURv
        YTFpRnpNMlJaVkJBamYwM1g5MVp1d28KAZBIri755JUbeZP2RZvXybR8YSb4OyE4
        CQ40VK6eJSgowU9D/+Xhn5V8dmEecUHFvGbeqwfoZtJmMzGzN8hb0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T17:59:32Z"
  mac: ENC[AES256_GCM,data:EsD1IOUoTRPzSl2IK2UAT3gepOyixlj6cn+Oal7Ll6Y2eN8Mmi2zk0KOLSlO7acQNXXKFLhfrtRAFAz3/vFwMzmXaDfwIn1NtD2J6xP3ZJAnMi6k3FEb0tFagLeOK/WxgbYKNz+kcPkO+I0USGON9ELf3olqT7dNHszw8uNTudg=,iv:dxkrjVT7iOUmIhE0APlX0JbN3Qc7ql7/xyUdZiYL9AA=,tag:uxlJ7G9CvodGwYdfFo5TIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
