# Local SOPS configuration for talos-cluster-shangkuei-lab environment
# This allows running SOPS commands from within this directory
#
# IMPORTANT: Replace the age public key below with your own key.
# Generate a new key with: make age-keygen
# The public key will be displayed after generation.
creation_rules:
  # Match input files for encryption (terraform.tfvars -> terraform.enc.tfvars)
  - path_regex: .*\.tfvars$
    age: age1s60r5ftjevd6pavaxldjs5j506r7wkekslqxxfhwuzu0zm0q7dgqcjq9ga

  - path_regex: .*\.enc\.tfvars$
    age: age1s60r5ftjevd6pavaxldjs5j506r7wkekslqxxfhwuzu0zm0q7dgqcjq9ga

  # Match backend configuration files (backend.hcl -> backend.enc.hcl)
  - path_regex: backend\.hcl$
    age: age1s60r5ftjevd6pavaxldjs5j506r7wkekslqxxfhwuzu0zm0q7dgqcjq9ga

  - path_regex: backend\.enc\.hcl$
    age: age1s60r5ftjevd6pavaxldjs5j506r7wkekslqxxfhwuzu0zm0q7dgqcjq9ga
