# SOPS Configuration
# ====================
# This file configures SOPS (Secrets OPerationS) encryption for the infrastructure repository.
# See: https://github.com/getsops/sops
# See: docs/runbooks/0008-sops-secret-management.md for operational procedures
# See: docs/decisions/0008-secret-management.md for the decision rationale

# SECURITY STRATEGY: Per-Environment Age Keys
# ============================================
# Each environment uses ONE age key shared across all services/modules within that environment:
# - unraid: Development/testing environment (ONE key for all Terraform modules)
# - prod: Production environment (ONE key for all Terraform modules)
#
# This provides:
# - Principle of least privilege (developers can't decrypt prod secrets)
# - Blast radius reduction (compromised dev key doesn't affect prod)
# - Separate key rotation schedules (prod quarterly, unraid annually)
# - Simplified key management (one key per environment, not per module)
#
# Generate keys:
#   age-keygen -o ~/.config/sops/age/unraid-key.txt
#   age-keygen -o ~/.config/sops/age/prod-key.txt
#
# Store private keys in GitHub Secrets:
#   SOPS_AGE_KEY_UNRAID  # Used for ALL unraid environment secrets
#   SOPS_AGE_KEY_PROD    # Used for ALL production secrets

creation_rules:
  # Production Environment Secrets
  # ===============================
  # Most restrictive - production key only

  # Terraform production secrets
  - path_regex: terraform/environments/prod/secrets\.enc\.json$
    age: >-
      age1rfcx42q24s257ycu6wjnsxyguq2dl3r99mmkau5zdz8g0lkxnppqhxlrwd

  # Terraform production variable files
  - path_regex: terraform/environments/prod/.*\.enc\.tfvars$
    age: >-
      age1rfcx42q24s257ycu6wjnsxyguq2dl3r99mmkau5zdz8g0lkxnppqhxlrwd

  # Ansible production secrets
  - path_regex: ansible/group_vars/production/secrets\.enc\.yaml$
    age: >-
      age1rfcx42q24s257ycu6wjnsxyguq2dl3r99mmkau5zdz8g0lkxnppqhxlrwd

  - path_regex: ansible/host_vars/prod-.*/secrets\.enc\.yaml$
    age: >-
      age1rfcx42q24s257ycu6wjnsxyguq2dl3r99mmkau5zdz8g0lkxnppqhxlrwd

  # Kubernetes production secrets
  - path_regex: kubernetes/secrets/production/.*\.enc\.yaml$
    age: >-
      age1rfcx42q24s257ycu6wjnsxyguq2dl3r99mmkau5zdz8g0lkxnppqhxlrwd

  # Unraid Environment Secrets
  # ===========================
  # Development/testing environment key

  # Terraform unraid secrets
  - path_regex: terraform/environments/unraid/secrets\.enc\.json$
    age: >-
      age1c7e6x6347t6v4y7ms0x90rkhr0evqy0n9khxnzlm3e6lynyqwezquejwkt

  # Terraform unraid variable files
  - path_regex: terraform/environments/unraid/.*\.enc\.tfvars$
    age: >-
      age1c7e6x6347t6v4y7ms0x90rkhr0evqy0n9khxnzlm3e6lynyqwezquejwkt

  # Shared/Generic Encrypted Files
  # ===============================
  # Accessible by both keys for shared resources

  # Generic encrypted files (use both keys for flexibility)
  - path_regex: secrets/.*\.enc\.(yaml|json)$
    age: >-
      age1c7e6x6347t6v4y7ms0x90rkhr0evqy0n9khxnzlm3e6lynyqwezquejwkt,
      age1rfcx42q24s257ycu6wjnsxyguq2dl3r99mmkau5zdz8g0lkxnppqhxlrwd

# Notes:
# ------
# 1. This file contains PUBLIC keys only and is safe to commit to Git
# 2. The PRIVATE key must be stored in GitHub Secrets (never in Git)
# 3. Encrypted files (*.enc.yaml, *.enc.json) are safe to commit to Git
# 4. For team access, add multiple age keys separated by commas
# 5. Rotate age keys quarterly (see runbook for procedure)
#
# Example with multiple keys for team access:
# age: >-
#   age1key1...,
#   age1key2...,
#   age1key3...
#
# Key rotation:
# - Generate new age key pair
# - Add new public key to this file (comma-separated)
# - Re-encrypt all *.enc.* files: sops updatekeys <file>
# - Update GitHub Secret SOPS_AGE_KEY with new private key
# - Remove old public key after verification
