#ENC[AES256_GCM,data:GyNc9NsgzBkx0LZcOUL87LBrDshL+ic59JeYA2zuznBkaEtZ3812NZkO3fp75rV8PiVBmW+jiCCzxg==,iv:JXr/2qEzxdFMsXiCSFEHb7uULkx5b29AxBeDo+pK98w=,tag:J+BRakmLiIs6iOSJl/9+Yw==,type:comment]
#ENC[AES256_GCM,data:QmoavBdzjV0G1bRJHkN6/ZGGmrdKk+/8PPyt177tQUZ+uzZid/VeYkWkCAs=,iv:EL+a4qcWs6W4Y3ieoGOqypqDANdZu7Tp7HBvlHYsR94=,tag:+SAiRBQT5hMWRw8AX9F2JQ==,type:comment]
#ENC[AES256_GCM,data:oL573wb/G29n0MN+T/eGpgCJ/BtKD1bKTEGjsqKhga+4eruVRIDGEDR+H3RWJUpePbGRVQ==,iv:ze3CbalIdfPTQu10+3DZfS0TYCO+fsof8TMh2zDf3xI=,tag:WlTgGhrzy2zzWiO2qiUo3g==,type:comment]
#
#ENC[AES256_GCM,data:R/1UnhcTdMExPWf/TjqO6VSO0GGtLcNV+/rQPubMuvEsXTPA1sF+NJSfz8HhZgydXGvCsPw=,iv:iJHrwLdfd1BNItefN5msjICXwZ1izV44sTfCfrmwUgY=,tag:9pLiQBVEC0mw4vBGa5fUAA==,type:comment]
#ENC[AES256_GCM,data:auuuw5DsaPeAbDJPJX5Sd0vvwJXJ7tTNYEA4FzufpbBcXJyTPFxPGzZSDAn7exYOwElcwH4yJKXVutWytzWbVV4=,iv:1PYbzVJpSqpkEFK3DH+5vCPnbRPvFgpWLMoP4BX9QK0=,tag:lQomwhkaQS9Kd/FQ6SMVKA==,type:comment]
services:
    tailscale:
        image: ENC[AES256_GCM,data:cUK9m2YEs4xWDVNc0vECoQS7Rqu/BApusCI=,iv:Wu+a0+6eL58HvcNBymIZvxiEjBWIBX0rlsZ2GPZGTok=,tag:kOi7fvWBhmNUlxLftzvH3Q==,type:str]
        container_name: ENC[AES256_GCM,data:m+WX283350RnLgIkz8nBrN5IU2Kx,iv:bE8j1w/77+QF95PHSg2ytkdYAS7hqK7LJyavSSWT3gY=,tag:g/I29MgRtjheGrL1gv4fkQ==,type:str]
        restart: ENC[AES256_GCM,data:EHIHB68ivvpeuWiLtfg=,iv:lynTQYbxI0K2FZj5/lI9FRiyI+UGE1fLTAf/3adoA80=,tag:smy96WqupcC3mZy2yVVhhQ==,type:str]
        cap_add:
            - ENC[AES256_GCM,data:63zvPzEwKpW9,iv:72Ko25Co6mEV2Q7sutWMyibtaxahmiSVrZbSK5DEQts=,tag:OJax73HCaYC/mMMaBKiyAg==,type:str]
        environment:
            - ENC[AES256_GCM,data:iFlFOnLSqAQkeVmJVwD65RWnhYzOt3ubIGyKTdh3dLTnZVjdDP8=,iv:4D+belojY9smwRWIhc539wG4rlnrzcjg3fVuYg7t4t0=,tag:t6hc11/eAdW00QU+Q+Y7ig==,type:comment]
            - ENC[AES256_GCM,data:GgFLoJ9ePnlTC1NdgBqFods1PCdOTMPU,iv:A2dqLPP7m0VLomjor2X+Iu9aIqmSQvv7uloqGUTodjM=,tag:x2AYLZY8wE1Was2yc6fIkA==,type:str]
            - ENC[AES256_GCM,data:m5IZOhMIyBCitaSKSrxP+vtfwHbpI3cDKh4nGA==,iv:hgV0eJy21Aze7zI7ob5XYhVAI0TGC9uZP12S04bOXOs=,tag:tnDiiG6qCx6rNvJzq63CUw==,type:comment]
            - ENC[AES256_GCM,data:jwxjC05pNavXob25IO6G1Bf+HYfQusslEnABTWG5wtQ=,iv:VEb7qItccEkQ6t4P/1XLSmYFpTLSXBbaB6uIfkujB5I=,tag:UDwVOzpVhF2o7zQ/0a7keg==,type:str]
            - ENC[AES256_GCM,data:rivXonNMJT4DQLgxc7eyABBAiOCN9mjjmg==,iv:XRspwsyJbOH3kyj4LIHfSXu5C+/vKd31/V8wA/6X+dk=,tag:rrLawt2QmUCwFeLE393YTg==,type:comment]
            - ENC[AES256_GCM,data:mZM5rdUuOEObPHAPYQo4WPbpF+BHVzqUJKe7j+5N/cctfA==,iv:hv5H5vZDpzi6UuYyBuD/LgHMDNQVoS6x1jN2ogyQYQw=,tag:MfTmjC4bZY1RhXHfblhPLQ==,type:str]
            - ENC[AES256_GCM,data:+z3m3TVpMOj0TBZzOyaLD/bp/Y7lhGCWPArOPIHk,iv:CGUghMPuAwMNi7skTV477Jqd95SAHFIppb9a5WWxJM8=,tag:LA8eoNFu0WonUcRO1oXx8g==,type:comment]
            - ENC[AES256_GCM,data:M8U48X27p/RWoocfjHN9s0tYeX8yvynuQRPUKF/pXA==,iv:tpxODjpmLa1EBcDcTafqo2PsUS1qMNoMd0oep7E1eIM=,tag:F8rEtT4awUoFG/k72aDpJQ==,type:str]
            - ENC[AES256_GCM,data:zC2yCAGTQ/dXqnxpz+8c7j7+l35c5uUfir5KuW+tpFBj,iv:+Bh68xFf3ZQ/NUxJKwdN6Y7Buz6CQQYOMj6P4pPbg0s=,tag:B4Zs7/o8gwaQED7D+nvxAQ==,type:comment]
            - ENC[AES256_GCM,data:52yH7u5ZwPmKJALxttLc4tXd,iv:UtJiVJCSUu8YwYvHhRRvQ1FbToWZtPbi1pR19ltP/wM=,tag:+fO8oL505ziSi8OI0HqCkg==,type:str]
        volumes:
            - ENC[AES256_GCM,data:mXF/1jqZBhV2nRBNAm6mVtwiKM9y9B30OcI=,iv:3hpHmcoewJeM+tXsNHKVHK7FK+p+XefHQD9kzGKVX1k=,tag:3AWJJ7Hqy/5bAKs7tlObWg==,type:comment]
            - ENC[AES256_GCM,data:+hkdIJsfPZDXgq4pPcwJb3rAxo1k5OzxyBtWVxKXiktQIxuDWia9BfexDMmxFIJMrqVJfS6dcQDLJA==,iv:TCTulUkIL69PaBuP+9NQC6+ab61anqBUXGjALQzfI3g=,tag:o8ECxOJz3lAPL6v9t5i+sg==,type:str]
            - ENC[AES256_GCM,data:2pbaletQbeO3dRWQqZoh2gmn390=,iv:p2VVxuRL0PYdFl2Bv4mfjGXR6c47klWwI9NY+g6VJK0=,tag:ABcBthCSMW1Odf9QTrjkCg==,type:comment]
            - ENC[AES256_GCM,data:FqvTQYKTCCQlZG75rcRnfkBZ3Z/NNAkdoMSrXA/fnRMdhNutERwrZVMuCl+Q9i/OZQ2lBGwWzcZ/vdtLT77bKLTpK1Udrn0pUnTbMuYgTdXvCg==,iv:JzjtlqHBQ7FeVlVdlL+M9PDu2RbdbnfV5QFmhnGnJuY=,tag:sRNOAIfgW1PG9mSCf7dEcQ==,type:str]
        devices:
            - ENC[AES256_GCM,data:C21eZ5s3pj8HkLMLkHsNgD6q7bq3T2rRzg==,iv:irzy5lwbmFL0t9oUnre3p60itvqG8O+UM2wNoAZ1VgI=,tag:7r8+QYFw22EEmLDZcD26xA==,type:str]
        networks:
            - ENC[AES256_GCM,data:r0/YzV4XLkxhVuo=,iv:eO3jwM51bOYKdIphebGwccE6Htu0qmZzXEtuxZMfDT4=,tag:ACuDAShFfrfcRcPswwZSuA==,type:str]
    #ENC[AES256_GCM,data:glP1EnzQnXPjWGV+9soq/jJHKVgG7yNb8bhutC0G+tJHUJ+wcvR95mnvQUR+nAbrnUhGtKYo7ua1dCNfkLQM,iv:ZjXiubhbrsHX2WFKI352ykUhAPZdYjuoK0VohIlU1fQ=,tag:OrOAeLqVn4jbg2xDgfFUrA==,type:comment]
    vaultwarden:
        networks:
            vaultwarden: null
            cloudflared: null
    #ENC[AES256_GCM,data:gnaYs7LBbh49sSeQPWEInTsoJZsJ2O00WgR3TfrJmh9NwRfA9wPPHuOqRaKOjGL6JKuXPvJaKw==,iv:WFvmWE9Fq3j6EEqbdhR911dhHij9HDCkcvYfC7cgQik=,tag:oEY5Jb8RlgmESn15ccnzfw==,type:comment]
    vwmetrics:
        networks:
            vaultwarden: null
            alloy:
                ipv4_address: ENC[AES256_GCM,data:bD5Lqk+sW1Yf08U=,iv:rm2QeM48N60QTAotfG4JO3e73wU70jZ9m6mzJd4AJSY=,tag:BqbZLdeN1+kyMyMgpCoNeA==,type:str]
networks:
    alloy:
        external: ENC[AES256_GCM,data:UwSVTw==,iv:KEeySdgRieEvKX2YGRyHQFH0b3WzAIMIgGmlskv8i1s=,tag:O0JByMNMWH82n0UMZfQxhA==,type:bool]
        name: ENC[AES256_GCM,data:wFmOvy7z3hWpGunkwUI=,iv:ZfqXpvZplRybHaiGi92kKzAXJ02Zic3xH5owdwARLpI=,tag:vtAd3ALRwYZXVz/3xqry5w==,type:str]
    cloudflared:
        external: ENC[AES256_GCM,data:r9xr4Q==,iv:r8Gwt8raffTUHi6ilvdExSruVHsCk6EyT18DIORFHSM=,tag:GrH6RMXQOQio1lfQTVKOKg==,type:bool]
        name: ENC[AES256_GCM,data:YVADz0WJrE5Q8ZpDtBZ5UO6Z/Cg=,iv:5GYjKccYBldEE8XfiMO4oLHsg3h9ZtEdlWI5AUcY8B0=,tag:CtRmV/eazTVvBvP+Kp5mDw==,type:str]
sops:
    age:
        - recipient: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ci9oNk5vOTlDaXFkaDRa
            azFQaGM0M0kvSlUvbHdaR1RQWnZCQTVyWVEwCkZzNlhEMjRqYWZPRTRKL2lUVmVi
            NVBWWkRLZytFb3FYRzFqTWJSczh6d00KLS0tIFRqOVhvekVxR1FUaEM4RGg3ZndR
            elhqNGdld01ITU4rcUJtZm4xSmxGWmcK007HYLYMKbnDVGwneFOLrBb5Js1xf4Af
            wML3clK3g6PgiFFptkwbOAJeBdaIf1GbMTRIBSGsM2UVNvLVlGDNZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T08:19:40Z"
    mac: ENC[AES256_GCM,data:HaSi62OPp9TkA9vVsXVec/gwgZu2Dr4vVN+kvsEAOpJEchXe1cnn4JsmaJQV3HPzzUiurH1ali5zkLsD7AKbfoD6ooLf9IwafgfSHybpbn0SaoxFeXnRue/p/Q+KZB2c2FZIGDJqaw/vfcvyFkE2do2oAZcH+EE21AL6OFKz73U=,iv:nQgnIYFXVFuA433kP6rSzZgMU5vkTBR4WoL0QBUMKbU=,tag:rPCRjvbzAaLU8jf3I/0AEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
