# Flux Git credentials secret (ENCRYPTED)
# Managed by Terraform: kubernetes_secret.flux_git_credentials
# Only stringData section is encrypted (metadata, kind, apiVersion are plaintext)
apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mu6SBklqQyu+R38zWTK2Zi/yIUyo,iv:oD9n70eyKyWO9eL4GFwYXvO6a4kTMnN60i3oodgwbIU=,tag:4zuPtEBVPHduBbZphO/IEA==,type:str]
    password: ENC[AES256_GCM,data:zWTTpz9o9JPv2vHk+Cmhr7+GT86Mf9JdQ/45FU4syaCOFf8tT5k4vg==,iv:wkdRnKUsFWJskv/hTv73pbYNCyj9zuSN4dAANex84/Y=,tag:0kNYjv0oOxyIwznrh2emBQ==,type:str]
sops:
    age:
        - recipient: age1xd9vrcj6n5nazq3tek8t89qxaky5eg9339phyddeemu99hqgvfcqkr2ysp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UEIrUWVQNHNVT1dtd3dw
            Vjc3ZGdhUU1DMmRtVFhQVTlTaXJlRDBvY0JNCkdLTmV0QTZDWUhMdVZ3UGhYNkZD
            dHpSZkdjZm5TR25JT0NxU1NQNUVHSUkKLS0tIEpNdWhybUZQOWcyYTN6ME45NGl5
            MjZEQkVDV0k3YVJ4SGVhQWpodVgwcXcKpRSIN1aKj/eualll00aWGxN9tMjJPyTv
            385EYcevxVJj7rgVKUhCKcPEpIxTNRlpn9wC2ZlQrInbKRzszefi6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:33:40Z"
    mac: ENC[AES256_GCM,data:UEiX1R52Rq1mbFL+/89+3Ntkz7GFyFFBxAH18jVKUMWnuiYAeiTo2l0O5hv4ePBIPS2DM8Lrdb0mnYsgRyH0fsviG6GxjLTHI9a+VUMSBorki/3OEwDUl8pyCgili8xIQm4kGj3cs13Puj1GdakX4dfUpQcuGiKSSa5YtkuN534=,iv:27BSboQrrYgP2kn2nLM3IUaeKUp73NaRfdS9/QyMJQI=,tag:jWhG1KyzyYiZBMnr4+E4pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
