#ENC[AES256_GCM,data:2BxwMjRcxLAy60VDMmxpf5BNy8atCuCyr1WAlfS+xjVYw+5n09JY7dMSY8TV51AjoxwXODFWEocePA==,iv:fsPhZZD6HgpMc52UZbFSeBnPLDtVTNjkLmSogvAhMZA=,tag:4/unr9ieoVQEF9e0rXQUjg==,type:comment]
#ENC[AES256_GCM,data:m3iGjC5LpVGSYLGpXN0C2xV1nWlLbmmsMtYc7t+irT1aghtzylJXuZtM+tE=,iv:SEyIp5q2QihnSnDHPo7YTRlSzpWVenm2OFo9gFYhFtY=,tag:7kztmKP5yuY1qWS7f5ZDrQ==,type:comment]
#ENC[AES256_GCM,data:lgkA+2Sb68LmNRscL6rdauSA9BmMGDrZJZELeVgx1urs9l53qROikX3P80NUuChBwn8n8w==,iv:83UC39aJG/Fd2O1iBi4WNgBIhuVOJQ/BaRpRLK/lipc=,tag:5BuTf4cBrnhLHZ+BiMxHyg==,type:comment]
#
#ENC[AES256_GCM,data:yVfJ3QV6I7yqEPP69cNeh+lG8PUBU8zpNwzf,iv:Xc2rI2mgDpUgXrA1YcUj/TtgyoZm9LwVeV7S0mhAV1k=,tag:ZRiSiWzt33igSzEEwr0fcQ==,type:comment]
#ENC[AES256_GCM,data:GpX5O8koNN+0kqMFPib9vQPGUvFzJ5XPA7U5yfMyUg==,iv:D+R9wQNu9sm2AqMl1j+Wll4T6D/8jTfy/owJ3fw9WWU=,tag:O+rtHfXyCVoonGZGgYvfgw==,type:comment]
services:
    #ENC[AES256_GCM,data:NRE/RVf6/oWb2Pni7cr46jlzuZzQPbBkBUuTvPpNbyMn9FvLAXSZMG4L12I=,iv:kWc2TAI4Q0ZCaQmAl8poXAfCGR+WJch2NWIOuLSOAmA=,tag:a2u/+E7JAX3xbt06mxgx4g==,type:comment]
    tailscale:
        image: ENC[AES256_GCM,data:Qad2kuBK1JL6Egl0kJ4x6sczVrV2oj1WKy8=,iv:JuxP9/iHlxcxxJEyIBU7RkbI3xwCW6d7mrfBvyuvITA=,tag:mEO9eQqwHPFItYydkjaoWA==,type:str]
        container_name: ENC[AES256_GCM,data:dtRRabxloWbH9OhBWGYk2LV+jG84,iv:x+ozCNwa/7lQzJeuFxrCAELU+66wgcWoekYQoEyRoPg=,tag:TGXVcpqSbkebzzF4MH008Q==,type:str]
        restart: ENC[AES256_GCM,data:x3rwX8U2nTzl1ZHztEA=,iv:cbApWdo8CR8Pks0SqogQTGaOIS5Du2k7XUgsLTHvXHU=,tag:iSZLR7Vz8Wjl+v9AditgIw==,type:str]
        cap_add:
            - ENC[AES256_GCM,data:/yn4nGbSnPeB,iv:OW5V3qcDvdfKhPyuLk/AhhVx3o0Ljy46kpHai3nZjBQ=,tag:mkvYQqLLtvrQUrCzDUUBIg==,type:str]
            - ENC[AES256_GCM,data:ADwKbuJXhQEtZQ==,iv:+dIWQ3BNEp6vw1tE1Xy4isXvc/Yu4QsRa4EUgNGiWIQ=,tag:BZdptLGNu/zIuMSdVW51/Q==,type:str]
        environment:
            - ENC[AES256_GCM,data:QjiuqW7Dvh870a0WIWpwkXnFUKsnr4T65x45dTY=,iv:7npunxxHgG8DS8awjzpGmzAUN5SlISy49aYE1I+rLAE=,tag:6g98aboBur5u6qiVfqb8lg==,type:comment]
            - ENC[AES256_GCM,data:f3xC0eDdwI/sMsH82sTW1JeAK0FU6Rkl,iv:27b+PQ8pCSHsAcdx7BYP1BpyiQ+9NbMM3+v2NRncBQM=,tag:VFXmG5I3slQnOZcLurj4iA==,type:str]
            - ENC[AES256_GCM,data:C+GZe6fhoUEQwRMi4HaDFjPsO8UbHuPTkJ5rMGKfbY/bFg==,iv:96xYEJJjrTb0m/mRMe5SqgcNEJh7XRk76jyikqZrrY8=,tag:ZGCze1itfeUE8KZ+IfcMxw==,type:comment]
            - ENC[AES256_GCM,data:IAUruPvQyRxHeYtw2h5YWUaCEJfMI4Pj9kJJalKq,iv:vzMGQrezTSjMY1X+YXfPivnhcUUBwtHDB9ox2r9BPKM=,tag:HIL80PaGbB1sqIoIPYqC1g==,type:str]
            - ENC[AES256_GCM,data:aojvCOtPlRM4eEE7f/exjg==,iv:85ZgbAsDgybLeq1r9qWyBn7IynuJ8YCaHhkd+SDasIk=,tag:u3FiRnoDhzlODFivKlvaYw==,type:comment]
            - ENC[AES256_GCM,data:7GfoX1uugiVsDjcrsnOp7pf5LoIJWM4NPujgSjgIog==,iv:1YdGLrhATOSVI3juZyiA2brdblAgdeZBV/xP+Ylgwe8=,tag:HVbyimktV0X49tPI9XC9hQ==,type:str]
            - ENC[AES256_GCM,data:upC9seYXw3iCwirGxSgwNYwQn0qjhSB14T2YBSHnDWtqk/6a,iv:hqDq1gpnY8LddCuOJ6Y+YjFIRWO+eIK0IzCPYEsRqQ0=,tag:YnHlgDEGsdHn5qi9hvc7Ig==,type:comment]
            - ENC[AES256_GCM,data:pT9fVCUGN2ZfHiWA2TzR0AHFk67MZRgpuAlKQaWiF02i3w==,iv:AaS2Y/abU6lfjWgUdtzD+Bzwwn/pbF8KhyTgq16smkI=,tag:dnV9gzW22Uqh6nUjL6c8Dw==,type:str]
        volumes:
            - ENC[AES256_GCM,data:8d6RkCKE5gc9tiYFiYNX2Hr0weAh6LYj1iPj/Q==,iv:vQKPT7JiafnPzg2IWHm6VjhLxaS+5Xtp98a0NPqEm8I=,tag:pMilhfC/P7Bc/+W3a4bUnA==,type:comment]
            - ENC[AES256_GCM,data:+X2qzY0S4+NsKc1GFiyEVFur7SZEpDh+FO8aqwMYnIRRu9Wv2H2cIbEgbpCcVHcsT0KesgD+Hwlq7g==,iv:H78nX3W0a0xqyH+wLU0wklmbBUlGgzxaxh4rc7Xck5w=,tag:iYoAbPcPujI1ZxrpD4t8xw==,type:str]
            - ENC[AES256_GCM,data:PsnS7O5CboC/TYd7gF9iGm8YMdo=,iv:IfT+faA3ooAIjOcC15FF/uwRY6rFBP70YL6IjpGJDYY=,tag:yHmpJ2MxnhuJqJU2EhvnIA==,type:comment]
            - ENC[AES256_GCM,data:09m8P/TKqo+tyvMLiVl+oLFhEYfZ9MCcKLcQKmd/P0S+HElmPluoYAHtgHQDjyZQtgR1ydPeDJpgZ+bNkAMkKCzEPNlEq7Yldo5DMBveLcG69w==,iv:VOytnEforHatt7+VDTNn2+gvyuLDGIoJFoO88jraULc=,tag:MtitJ3Wk9tvzcHSXdeIEMg==,type:str]
        devices:
            - ENC[AES256_GCM,data:ZakY8cNJMGTzP+AYYLTwUTF6NA85w2vgLQ==,iv:GgiewloTpZWuEV7LtS9VWarBOGmSUI6bXILE1RMLI8w=,tag:NLasIx+ZihPHtv+PhgueOQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:vp0psvVIwBnJ+oA=,iv:dRCihbnmMZe6jJ1aJSY4udT3KR5XxN4sOy+tEkUgnWg=,tag:6whvLsbs3eLwBpWnTfBrEw==,type:str]
    #ENC[AES256_GCM,data:SvZMTuTdPEKkvYO5/jSkyNY5RMwJ2fiyGLEhsLx9z88bHY6U/ZIkQeFgk+pIRg3kPUqkoKgLfDYpQoxRTbJQ,iv:6PYdro5/2VyxVk1lgYIPD/noemaiTLjRZzwT2q8cbBA=,tag:jjQsC5vpuOzkBzD13CmXjw==,type:comment]
    code-server:
        networks:
            code-server: null
            cloudflared: null
networks:
    cloudflared:
        external: ENC[AES256_GCM,data:o6H+6A==,iv:hn6ZnlZItA8nOaby27DnDuMwileGG2uPFjWSgPHxfPw=,tag:kilZMdKXJ1mQvdWYoLaZFw==,type:bool]
        name: ENC[AES256_GCM,data:X89BeNzRnoAGJWuopEjjuPB+1pY=,iv:ZEuZn/1kbuHhpfY7UF/LvlHsXUfCRrZJm+gDmImIb1c=,tag:nZ7ibC4N45G6rQ3pu8YFqg==,type:str]
sops:
    age:
        - recipient: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWER2ZmdCeENGa3N6V1ZM
            OTdpZDF0Ykh5eWRLTnhwNDA1VS9ZeEFGNmdNCmllMmtGbFp1djdNMUJscEhGcnEv
            c3BEcWtCamZXME9ZSVpzRHE4Z3ptb3cKLS0tICtIclBqQ2ZzN3JwVTBGSWRLTUJW
            MXNzYjl3VW1KS0NUTVd1dnB3Um02MnMKxTnavfDLbEfTaeLfR6UNzccZiKzpJmK1
            iPVrBgAs/K9sWeB/kA1YO8z2UJ0Imkv5rR6UdSMnd546TEigrrAZ/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T07:31:31Z"
    mac: ENC[AES256_GCM,data:q3nsR8wXnz7Htz2TJpQI32VxI9o9E0wptKqTzXqdc0x1ssCjPo4X4yd26cjx9H4+HJMjRpJ+yCLtoYvq+4Lgg052n2bXkiyJZul5Hlx3qha8n+hFcygmjEm7sKTv6J9RNeGrjqd3StjiPxPHm6SsJp/HQfWTmX5kLYvpWKiMEK8=,iv:h4sDcup47TiZAKjOKBrTne06f/PR5fF+uouNtDvUPfY=,tag:8vBAvGxKmxSc9MUhLMCz4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
