apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: edatw-ed8-notify
spec:
  storageClassName: edatw-eda-smb
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0750
    - file_mode=0640
    - uid=999
    - gid=999
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: ENC[AES256_GCM,data:SE8nSLjflfLE9xRiiqctQH1I7+Koc3PNmIBBB3E=,iv:MhBaLXEgeiWY7EJrCjYMTHpLFmgI1H9sHqfChHYKbYY=,tag:HtRDc8dmU054We7WpeQ8NA==,type:str]
    volumeAttributes:
      source: ENC[AES256_GCM,data:dC+RZSpaK9EHuzbT0VACP9eVbgg9HmzrAAodVguzNraAY8c=,iv:94Yj0GBC4PonLsNkC1hwXzKSMeqGr5snxMCtilu+RWo=,tag:jPAsc1eZ/oPLQKsd5tmvBQ==,type:str]
    nodeStageSecretRef:
      name: ed8-creds
      namespace: edatw-ed8
  claimRef:
    name: edatw-ed8-notify
    namespace: edatw-ed8
sops:
  age:
    - recipient: age1dvf63gewxhnydzt4yjlpp23qplqekt979udv4xgk47zct48kh40srrdjwn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUnpaeTFsdVZHeERsblZl
        ZWRVeU8ydktmRGptbTFWbXBPZXhrT1YvS25BCml0UitjKzg2U1ZLQnBqS3ZQbDBR
        dlRFdTd1ZnNuejV2SFA3WWhQMzZpWVkKLS0tIFZQWlBhZzEyZ0d4UGNoVlJ1MzZu
        NEtUaFV4OFZ1NFgyMXhvbEdCdkVMaE0KZx7PJfDtnMhi9U0mdLue+/ih7Yjl9RXv
        uot2FM5Rph93mVkq4pItOiAMCddeHdSg36KVlXPMaJCWnOOCUfIhcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T14:13:41Z"
  mac: ENC[AES256_GCM,data:2SUtPqpEyAxFRU3wIH4o8EI5RWiSStuxQwxGKDTOTRgd53CkyXRH1K2OtRFP3SvStVxGo7Muc85NwKRHl86z8KfRzxAgG5uB8dFhGLdbZO/CieiqGDqJCX+nkCH7kIavW0tZa6us+y9vxIPk9Ewz29ma2zpiboH7aVfFTS+oNos=,iv:bqLkHuChMNk7o2b728mRfF0JIpVpjEloXNC2+arYSL0=,tag:zG5d3IQlePzs/LNfINqd0A==,type:str]
  encrypted_regex: ^(volumeHandle|source)$
  version: 3.11.0
