apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: edatw-ed8-backups
spec:
  storageClassName: edatw-eda-smb
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0770
    - file_mode=0660
    - uid=999
    - gid=999
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: ENC[AES256_GCM,data:onCWRylP87sSLeNAfa1kUpSzLc1jxAtXI08=,iv:oyN/i5HAbksIHltUGGiu99bZJA+S+qgzwdYb72hFf5w=,tag:UqaY3YYTZMJcCf9LXjlEnw==,type:str]
    volumeAttributes:
      source: ENC[AES256_GCM,data:5+3nwtlGLLHEFjlotl8lq0mrmsgBo1OHw8V/3w==,iv:pjAvgVkcbFdnJjmzexCb69dPAw0/AkGeUNgQzugv+f0=,tag:RN/8XKijZWp2d52XHPxStA==,type:str]
    nodeStageSecretRef:
      name: ed8-creds
      namespace: edatw-ed8
  claimRef:
    name: edatw-ed8-backups
    namespace: edatw-ed8
sops:
  age:
    - recipient: age1dvf63gewxhnydzt4yjlpp23qplqekt979udv4xgk47zct48kh40srrdjwn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc1V1MmZEaXRLWTYvaEI1
        aVBBQlpNb3UrYXFycGJTd2JQSHVCbmRYSlZrClRqdWhJSkUvMUMwMWYwVzZJdk9t
        eWNLdTBsUmFZSDZiRzlIWEUyVjIyOVkKLS0tIDEyeS9GZXRNR1F5RXZiOWlhSkxN
        YmpXc3pubElrS2huQzdtMTNPK3RVc0UK9w6jVCwk1wj1uDWF8er2GlhRXmdZm90x
        47y9riWm1C3Y2vCwdPCQMEKYujyBhrznawfoDbdXMLco8L2nYj59Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T13:55:26Z"
  mac: ENC[AES256_GCM,data:PZCtzppatIXphI3WIX/bWz60VPgSE9fgr4QTB1nPp5Ss4+274SS8GEiagFMTkDvaLXSqphhex2wyOoAPo8rNWCCRt3aVafyy9HuLtkqS+WCbR4WzpetGg/KLka7dgOFOEJjvodYHWhns2VpvE3uwTeFxtqNDmsVU0KOlaiKSlqg=,iv:rQRcx0uIwtiRyycai7vlUkr9nVoBjGX7A3Wsg4upYgg=,tag:wQu0L1u0iu2m7RyUUTQMwA==,type:str]
  encrypted_regex: ^(volumeHandle|source)$
  version: 3.11.0
