#!/usr/bin/env bash
# Build Grafana dashboards from kube-prometheus jsonnet
# Prerequisites: jsonnet, jsonnet-bundler (jb), jq
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/output"
MANIFEST_FILE="${SCRIPT_DIR}/../grafana-dashboards-kube-prometheus.yaml"

cd "${SCRIPT_DIR}"

echo "==> Installing jsonnet dependencies..."
jb install

echo "==> Building dashboards from jsonnet..."
rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"
jsonnet -J vendor -m "${OUTPUT_DIR}" dashboards.jsonnet

# The jsonnet output is a JSON-encoded string, decode it to proper JSON
echo "==> Decoding dashboard JSON files..."
for json_file in "${OUTPUT_DIR}"/*.json; do
  # Parse the JSON string and output proper JSON
  jq -r '.' "${json_file}" > "${json_file}.tmp" && mv "${json_file}.tmp" "${json_file}"
done

# Fix Loki dashboards for SSD mode
# The loki-mixin doesn't properly replace container-based resource queries for SSD mode
# In SSD mode, all containers are named 'loki', so we filter by pod name instead
echo "==> Fixing Loki SSD mode resource queries..."
for loki_dashboard in "${OUTPUT_DIR}"/loki-*.json; do
  if [[ -f "${loki_dashboard}" ]]; then
    # Replace container patterns with pod patterns for SSD mode
    # distributor/ingester -> loki.*-write.*, querier -> loki.*-read.*, backend -> loki.*-backend.*
    sed -e 's/container=~\\".*distributor.*\\"/pod=~\\"loki.*-write.*\\"/g' \
        -e 's/container=~\\".*ingester.*\\"/pod=~\\"loki.*-write.*\\"/g' \
        -e 's/container=~\\".*querier.*\\"/pod=~\\"loki.*-read.*\\"/g' \
        -e 's/container=~\\".*backend.*\\"/pod=~\\"loki.*-backend.*\\"/g' \
        "${loki_dashboard}" > "${loki_dashboard}.tmp" \
      && mv "${loki_dashboard}.tmp" "${loki_dashboard}"
  fi
done

echo "==> Generating GrafanaDashboard CRs..."
cat > "${MANIFEST_FILE}" << 'EOF'
---
# Grafana Dashboards from kube-prometheus jsonnet
# Auto-generated by: make dashboards
# Source: https://github.com/prometheus-operator/kube-prometheus
# Do not edit manually - regenerate with 'make dashboards'
EOF

for json_file in "${OUTPUT_DIR}"/*.json; do
  filename=$(basename "${json_file}" .json)
  # Convert filename to valid k8s name (lowercase, replace _ with -)
  name=$(echo "${filename}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')

  # Determine folder based on dashboard name
  folder="Kubernetes"
  if [[ "${filename}" == loki-* ]]; then
    folder="Loki"
  elif [[ "${filename}" == *"grafana"* ]]; then
    folder="Grafana"
  elif [[ "${filename}" == node-* ]] || [[ "${filename}" == nodes ]]; then
    folder="Node Exporter"
  elif [[ "${filename}" == *"prometheus"* ]] || [[ "${filename}" == *"alertmanager"* ]]; then
    folder="Prometheus"
  fi

  echo "  - ${name}"

  cat >> "${MANIFEST_FILE}" << EOF

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: kp-${name}
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  allowCrossNamespaceImport: true
  folder: "${folder}"
  resyncPeriod: 24h
  json: |
$(sed 's/^/    /' "${json_file}")
EOF
done

echo "==> Generated: ${MANIFEST_FILE}"
echo "==> Dashboard count: $(grep -c "^kind: GrafanaDashboard" "${MANIFEST_FILE}")"
