#!/usr/bin/env bash
# Build Grafana dashboards from kube-prometheus jsonnet
# Prerequisites: jsonnet, jsonnet-bundler (jb), jq
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/output"
MANIFEST_FILE="${SCRIPT_DIR}/../grafana-dashboards-kube-prometheus.yaml"

cd "${SCRIPT_DIR}"

echo "==> Installing jsonnet dependencies..."
jb install

echo "==> Building dashboards from jsonnet..."
mkdir -p "${OUTPUT_DIR}"
jsonnet -J vendor -m "${OUTPUT_DIR}" dashboards.jsonnet

# The jsonnet output is a JSON-encoded string, decode it to proper JSON
echo "==> Decoding dashboard JSON files..."
for json_file in "${OUTPUT_DIR}"/*.json; do
  # Parse the JSON string and output proper JSON
  jq -r '.' "${json_file}" > "${json_file}.tmp" && mv "${json_file}.tmp" "${json_file}"
done

echo "==> Generating GrafanaDashboard CRs..."
cat > "${MANIFEST_FILE}" << 'EOF'
---
# Grafana Dashboards from kube-prometheus jsonnet
# Auto-generated by: make dashboards
# Source: https://github.com/prometheus-operator/kube-prometheus
# Do not edit manually - regenerate with 'make dashboards'
EOF

for json_file in "${OUTPUT_DIR}"/*.json; do
  filename=$(basename "${json_file}" .json)
  # Convert filename to valid k8s name (lowercase, replace _ with -)
  name=$(echo "${filename}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')

  # Determine folder based on dashboard name
  folder="Kubernetes / kube-prometheus"
  if [[ "${filename}" == *"node"* ]]; then
    folder="Node Exporter / kube-prometheus"
  elif [[ "${filename}" == *"prometheus"* ]] || [[ "${filename}" == *"alertmanager"* ]] || [[ "${filename}" == *"grafana"* ]]; then
    folder="Prometheus / kube-prometheus"
  fi

  echo "  - ${name}"

  cat >> "${MANIFEST_FILE}" << EOF

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: kp-${name}
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  allowCrossNamespaceImport: true
  folder: "${folder}"
  resyncPeriod: 24h
  json: |
$(sed 's/^/    /' "${json_file}")
EOF
done

echo "==> Generated: ${MANIFEST_FILE}"
echo "==> Dashboard count: $(grep -c "^kind: GrafanaDashboard" "${MANIFEST_FILE}")"
