#!/usr/bin/env bash
# Build Grafana dashboards and PrometheusRules from kube-prometheus jsonnet
# Prerequisites: jsonnet, jsonnet-bundler (jb), jq
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/output"
ALERTS_OUTPUT_DIR="${SCRIPT_DIR}/output-alerts"
DASHBOARD_MANIFEST="${SCRIPT_DIR}/../grafanadashboard-kube-prometheus.yaml"
RULES_DIR="${SCRIPT_DIR}/../prometheusrules"

cd "${SCRIPT_DIR}"

echo "==> Installing jsonnet dependencies..."
jb install

echo "==> Building dashboards from jsonnet..."
rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"
jsonnet -J vendor -m "${OUTPUT_DIR}" dashboards.jsonnet

# The jsonnet output is a JSON-encoded string, decode it to proper JSON
echo "==> Decoding dashboard JSON files..."
for json_file in "${OUTPUT_DIR}"/*.json; do
  # Parse the JSON string and output proper JSON
  jq -r '.' "${json_file}" > "${json_file}.tmp" && mv "${json_file}.tmp" "${json_file}"
done

# Fix Loki dashboards for SSD mode
# The loki-mixin doesn't properly replace container-based resource queries for SSD mode
# In SSD mode, all containers are named 'loki', so we filter by pod name instead
echo "==> Fixing Loki SSD mode resource queries..."
for loki_dashboard in "${OUTPUT_DIR}"/loki-*.json; do
  if [[ -f "${loki_dashboard}" ]]; then
    # Replace container patterns with pod patterns for SSD mode
    # distributor/ingester -> loki.*-write.*, querier -> loki.*-read.*, backend -> loki.*-backend.*
    # Also fix log filter: |= "level=error" (substring) -> | logfmt | level="error" (field filter)
    sed -e 's/container=~\\".*distributor.*\\"/pod=~\\"loki.*-write.*\\"/g' \
        -e 's/container=~\\".*ingester.*\\"/pod=~\\"loki.*-write.*\\"/g' \
        -e 's/container=~\\".*querier.*\\"/pod=~\\"loki.*-read.*\\"/g' \
        -e 's/container=~\\".*backend.*\\"/pod=~\\"loki.*-backend.*\\"/g' \
        -e 's/|= \\"level=error\\"/| logfmt | level=\\"error\\"/g' \
        "${loki_dashboard}" > "${loki_dashboard}.tmp" \
      && mv "${loki_dashboard}.tmp" "${loki_dashboard}"
  fi
done

# Fix Node Exporter USE dashboards - remove != 0 from error queries
# The USE (Utilization, Saturation, Errors) methodology uses != 0 to filter errors,
# but this shows empty panels when there are no errors. Showing 0 is more informative.
echo "==> Fixing Node Exporter USE dashboard error queries..."
for node_dashboard in "${OUTPUT_DIR}"/node-*.json "${OUTPUT_DIR}"/nodes.json; do
  if [[ -f "${node_dashboard}" ]]; then
    # Remove != 0 from specific error metrics only:
    # - instance:node_network_receive_drop_excluding_lo:rate5m
    # - instance:node_network_transmit_drop_excluding_lo:rate5m
    # - instance:node_vmstat_pgmajfault:rate5m
    # Pattern: metric{labels} != 0" -> metric{labels}"
    sed -e 's/\(instance:node_network_receive_drop_excluding_lo:rate5m{[^}]*}\) != 0"/\1"/g' \
        -e 's/\(instance:node_network_transmit_drop_excluding_lo:rate5m{[^}]*}\) != 0"/\1"/g' \
        -e 's/\(instance:node_vmstat_pgmajfault:rate5m{[^}]*}\) != 0"/\1"/g' \
        "${node_dashboard}" > "${node_dashboard}.tmp" \
      && mv "${node_dashboard}.tmp" "${node_dashboard}"
  fi
done

echo "==> Generating GrafanaDashboard CRs..."
cat > "${DASHBOARD_MANIFEST}" << 'EOF'
---
# Grafana Dashboards from kube-prometheus jsonnet
# Auto-generated by: make build
# Source: https://github.com/prometheus-operator/kube-prometheus
# Do not edit manually - regenerate with 'make build'
EOF

for json_file in "${OUTPUT_DIR}"/*.json; do
  filename=$(basename "${json_file}" .json)
  # Convert filename to valid k8s name (lowercase, replace _ with -)
  name=$(echo "${filename}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')

  # Determine folder based on dashboard name
  folder="Kubernetes"
  if [[ "${filename}" == loki-* ]]; then
    folder="Loki"
  elif [[ "${filename}" == *"grafana"* ]]; then
    folder="Grafana"
  elif [[ "${filename}" == node-* ]] || [[ "${filename}" == nodes ]]; then
    folder="Node Exporter"
  elif [[ "${filename}" == *"prometheus"* ]] || [[ "${filename}" == *"alertmanager"* ]]; then
    folder="Prometheus"
  fi

  echo "  - ${name}"

  cat >> "${DASHBOARD_MANIFEST}" << EOF

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: kp-${name}
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  allowCrossNamespaceImport: true
  folder: "${folder}"
  resyncPeriod: 24h
  json: |
$(sed 's/^/    /' "${json_file}")
EOF
done

echo "==> Generated: ${DASHBOARD_MANIFEST}"
echo "==> Dashboard count: $(grep -c "^kind: GrafanaDashboard" "${DASHBOARD_MANIFEST}")"

# Build alerts/rules from jsonnet
echo ""
echo "==> Building PrometheusRules from jsonnet..."
rm -rf "${ALERTS_OUTPUT_DIR}"
mkdir -p "${ALERTS_OUTPUT_DIR}"
jsonnet -J vendor -m "${ALERTS_OUTPUT_DIR}" alerts.jsonnet

echo "==> Generating PrometheusRule CRs..."
rm -rf "${RULES_DIR}"
mkdir -p "${RULES_DIR}"

for json_file in "${ALERTS_OUTPUT_DIR}"/*.json; do
  filename=$(basename "${json_file}" .json)
  # Convert filename to valid k8s name (lowercase, replace _ with -)
  name=$(echo "${filename}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
  output_file="${RULES_DIR}/prometheusrule-${name}.yaml"

  echo "  - ${name}"

  # Convert JSON to YAML PrometheusRule CR
  cat > "${output_file}" << EOF
---
# PrometheusRule from kube-prometheus jsonnet
# Auto-generated by: make build
# Source: https://github.com/prometheus-operator/kube-prometheus
# Do not edit manually - regenerate with 'make build'
EOF

  # Convert the JSON PrometheusRule to YAML and append
  jq -r '.' "${json_file}" | yq -P >> "${output_file}"

  # Fix namespace: all rules should be in monitoring namespace
  sed -i '' 's/namespace: default/namespace: monitoring/' "${output_file}"
done

echo "==> Generated: ${RULES_DIR}/"
echo "==> Rule count: $(ls -1 "${RULES_DIR}"/*.yaml 2>/dev/null | wc -l | tr -d ' ')"
