#ENC[AES256_GCM,data:dTMQHtl9AuMfXpbgV7VPPsYLar6lhksO0e/yD811JcTpb+Dw4pbEGwoUgr5wB/PZvPf+xXY=,iv:v/N8pWaBoI0FQh+c5D13u8GK/n5zbwPCkYXKCc4ycPo=,tag:24Rv5RKHQhRpZFaepdLTig==,type:comment]
#ENC[AES256_GCM,data:zq8gJtg9Re7eId+7Vy+XY9VGxRfNRyKeO81+WXdOmjdT18SzM/I/PQVRInY=,iv:XFcQfxR3fskc3iO5942rw8w+jytL/g/iMDakPUy9ddg=,tag:I7z2No5lJKKQ5/mWdoMkag==,type:comment]
#ENC[AES256_GCM,data:2azaMkbQ7fEI5dcORigsnir0x1q+LEf9Wup7+TIcMSGMUAe3+yhoy6Bics1az+/7fodJoA==,iv:sKspSe7NiAEpGuxGbdFuyU204ryJtjql7cWTHYg3FAc=,tag:6oRxiTHBGzYGmTroEctPMA==,type:comment]
#
#ENC[AES256_GCM,data:mPn/2bTcZc3rJTLpHHrsbT8a8/at,iv:dNQPe7zsd5Wk9WOyXuBmy2IqpRbWQVYAM1BPa6aK5p0=,tag:tZjAJ1iEt/iUW93QukYVHw==,type:comment]
#ENC[AES256_GCM,data:A31tvqP9wyAKdyRdD/JwYN0UWTn8Kf3TvNOSOVJX/931JMcaZHX7cS6yZPXE/jB8vLs=,iv:nK34LYsVPML4xGEStZNr7lR1zMNjSWC8ujggTNN5yBo=,tag:OCz7s1WLe5wWQJywPtxpww==,type:comment]
#ENC[AES256_GCM,data:lx+LX8gtBBSqZvmHZyfiFumTjr1bg2VKeTP4ShOCK0T+BthT1DXI6ciNEQAGggsldtxIqFG0855P2xeuXaA=,iv:45FNOS5GAN81om3+EPpVBQzWPW5grpLFoyb5EoJ2Ywo=,tag:GeKyRMUyVl1O9f1Cn0tghg==,type:comment]
services:
    tailscale:
        image: ENC[AES256_GCM,data:a6PyRAISzC86/bETK3vD86Ze1Ty0+AtoMoM=,iv:nGQduAo/LLgRQYDP+ovzcQeYQubYL9YX0C5StkvaQ5k=,tag:JJRRv9MrO0FY8/u7GjLDCg==,type:str]
        container_name: ENC[AES256_GCM,data:QVpPVnl60MCCXoOgaHz1Fg==,iv:IW+aadQQ/meWcFsgu0nVglqk61rRipRGj15AiF4rGIk=,tag:JCgTOZW8wLlmHNesQ7BJlw==,type:str]
        restart: ENC[AES256_GCM,data:iTj3ff6xLXAr0fGqp5I=,iv:s0+azWSUio6UNK/MZfUjM9gVivnU5fXOY00ZphJloIY=,tag:roOyvkyiX96W3obX7uedqw==,type:str]
        cap_add:
            - ENC[AES256_GCM,data:OsbIpe7ecne4,iv:IeStmq2fsJejsmmGdV2DpllIhBsqz99T7nVrh2B/t5o=,tag:r83DZIoHIwDMfKx7yNN0Hg==,type:str]
        environment:
            - ENC[AES256_GCM,data:mF8vdVQDnsAOP0J8odewN8lnZK350+4ebUcg0K31Resjd8hX/10=,iv:nSlWU+9Pm/zAyzMbSqmOGwdWftfDgNQm1gccL1DjabA=,tag:TdYBM7nG1II/vzc1Ffnmxw==,type:comment]
            - ENC[AES256_GCM,data:BRq04wKDT8+XC85c6jYutCp1zpPoh19n,iv:5vfK+Jp/yQ/jS+DAvn3f/hIkNwCwyIApWkQBEijgyws=,tag:iaf2h36p4fWX5rHP8A3+Dw==,type:str]
            - ENC[AES256_GCM,data:OXxdpxLsUb+LyaIXkFuRYnd2alLJgBJdzGhWV/C7kdwf,iv:lNdnUC1VnSVBVPFTvFWxt1vjx8Ngmuvi0vfI4x86BfU=,tag:xRIdyGGZcZetqs0sL/s1iA==,type:comment]
            - ENC[AES256_GCM,data:YajMPflEYavxyi9LogixUnK0sv07taIcfwvaB4DBs1SPoQ==,iv:ceS6vRJzhzHuqaG8cVy3/YDoXzQXhnET88ViIPLGJn8=,tag:IS1d17/NuvsWsEjyx8TKXQ==,type:str]
            - ENC[AES256_GCM,data:4PhFr1T6xAAT5E3J+KScFfli9Sq9/fK7gpt1a5vHyzbOx/jw5lQ=,iv:16+Xq4GR2MpajycPw89EVw9oxTjYcRJr/L3XyY37S54=,tag:qHqIgty0K5xozCLHTE9SEA==,type:comment]
            - ENC[AES256_GCM,data:D25nRZPNMGRu4Y5e4n+EWB3J,iv:bn3Os++9vYrUgaOFsxs0n5AC/vNoEd4s1zZ2QYr6RkA=,tag:U7X/e3IOty7NKdfI4XVN7g==,type:str]
            - ENC[AES256_GCM,data:GKk8/qox7lL142k4vIg=,iv:dDk6i8rtuuld0JJQIdZGUXghFMJapucDfhTofe2F5t8=,tag:TrIRpuFYC6sqspgRnaCdKw==,type:comment]
            - ENC[AES256_GCM,data:ao/7DqezboAezsLZYQfsObDMZbJ0s+pUBuwHQZKDXA==,iv:X5m16C2W1a3pVX6yXjaKmAkcHySAIHODMHHglotSJm0=,tag:iPQgklZ9m0ZGuhcdmDyNcA==,type:str]
            - ENC[AES256_GCM,data:dQVMATd+CbNXKrudphtapMyh6+GjJKclTQ==,iv:oE+LIlZ5//XDpDldP8VNbcX6lh0WJYWzrcpHAUhWm+E=,tag:mLZUmRWwDv/wTy3tzP5n5g==,type:comment]
            - ENC[AES256_GCM,data:sUA4WofQK2F0EWi5ExzVR+onvy1lRu7EdZ0eqUnZSEM=,iv:7gqhccY9zzEc0HdMAH07ZfvP/OUND4x5+S2K4e09b3U=,tag:o2LwFoUmsX+RkZIcukhQWQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:l/58Gz6Ai8o/iOAdBjePT2bnVb/9RVQWK4Wgsw==,iv:vsQNmkV/iqvP2JucpFxVCXKhjIjFFGPteNE+AcyIF1I=,tag:sENNTJF1/a3QNOvi/fUuaw==,type:comment]
            - ENC[AES256_GCM,data:Lfbq3p6cydTdqfbdxulPK+oPisDSwjoFk22Q4O1aVenbxLyaZR4GZSWZaBcOl9ILWvgFBHg=,iv:PHFon9MD6e89cUvBmoB2K3gHnHSRSsfkNUqkAN05qnA=,tag:F6wFoNvt5VTzcfzN8WWj+Q==,type:str]
            - ENC[AES256_GCM,data:vzLxgujPG8BfVSgTa5Zhv1zkj7s=,iv:wODCp4gRNFi7JnLrV/q/FF2oOrEsv/xh8DV/MqZSxAg=,tag:EiVDLTnyRrgZjqF9dfeWBA==,type:comment]
            - ENC[AES256_GCM,data:4uv6IILHJ213ozDhghUSaHKplWOT36sTS8itwKK23oS+/coxArGfB1r5vdPtsvUdP7HjxPMiKO0Lsf4sVhvrFrnunAOI7LJp97hZCYM=,iv:h4WUT51MaEOkpKPqK3+inktFnkO01RHPB13a/RVQV+4=,tag:ZX5BS1FmNRgPOPO4NccABA==,type:str]
        devices:
            - ENC[AES256_GCM,data:9IsgDjGLUCgMd8DwrQwaqBM6zdxTMkg2JQ==,iv:XnsUIaAZOaRALMB/COTZGKIpnxBN2pP5phmi2UBddAI=,tag:h4vW+5BLv0iZEyr8boJgBg==,type:str]
        networks:
            - ENC[AES256_GCM,data:wBZOO1g9,iv:r0eUtQN54bEpPTvFEHjHs5KKxuX8MGdcGpgPe32RGd0=,tag:dXm4zL/8zDUMjpDb8wRtcg==,type:str]
    #ENC[AES256_GCM,data:gFFrVU87d0/7Y8ZZpDgwtrJ5ll8J3IULHNxpB/UCWqRiooUehP2t8f5rrUWf43TJVjmWvL5KL2CkJ3knBzIIcws=,iv:NMZsMp8TZwtjhcyXu6AGPmbcwR1DgPQB+BXQz8mPulw=,tag:HkPpQrcBo/B/TUJ7nJ45dA==,type:comment]
    immich-server:
        networks:
            immich: null
            cloudflared: null
networks:
    cloudflared:
        external: ENC[AES256_GCM,data:Hz3qnQ==,iv:J0Vnelf+7bdQm7jsZdQCHldupKBG0hdHq7VUbXuCeX4=,tag:1FDCYem4bonue2JBYhIUXQ==,type:bool]
        name: ENC[AES256_GCM,data:Vfrxm38VKUGNrMnp0FGxnaI4LLU=,iv:bSZ0UotbARfXQWcv0j3a8PFMflAJfjJ8AdeclIdXt+I=,tag:bGEEq56Mfw0YbpJa5PwoAw==,type:str]
sops:
    age:
        - recipient: age18pns8av0m2g3wgenjnfkj046340azfytlp0jgpkw4dw7zkh83dwqlct4np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZ2U2U2xlb0lqRXRNRnZN
            YmxVWitpS0cyakdHM3NlTkloNUwwUGhQTVEwCmhxdDdGdG9GRGw4TFN6c1pkZXBt
            bDlSTU5GSnJHRnZFNjFGTnVMTEVEOVEKLS0tIGVBVWlFZFRUVURuQ2RYQTZNY1hF
            WGhHSVN3VUUrVFF2TUNWa1U5cnBWYkEKiInAl8TBr1uL9+iZh7zi/ZPFzTAcxQAU
            gxmvBFQ/U/nUsVw6hKDXtYYjDy6+vyWAiVagR8cBfRxmIpx9238ScQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T08:59:22Z"
    mac: ENC[AES256_GCM,data:ubCOpVcj7DH4MxReGWPPN5/5CGgq0CgxG7WQSbx0LmBiglEyACNR93R3HoSuJvtQytgV5IMfoUHFC2a3U71ja0XED1iBtOUgEzZqBLnPnMiQD9zZjygNbQ5w06StbNC8qUjVF69CLgC15s7x/l24B/r5jBl0Zh9p1Tc2TDxLg1A=,iv:Lqd9EKaOGs2LWbrb1nPwhf7tavb1Qfgn833WdN0VdrU=,tag:gWbINVqBxN/g3fX+gSLl2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
