---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edatw-ed8-image
  namespace: edatw-ed8
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: edatw-eda-smb
  volumeName: edatw-ed8-image
