---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edatw-ed8-database
  namespace: edatw-ed8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
