# Local SOPS configuration for gitops-edatw-cluster environment
# This allows running SOPS commands from within this directory
#
# IMPORTANT: Replace the age public key below with your own key.
# Generate a new key with: make age-keygen
# The public key will be displayed after generation.
creation_rules:
  # Match input files for encryption (terraform.tfvars -> terraform.tfvars.enc)
  - path_regex: .*\.tfvars$
    age: age16v3c6ulmkwr2nav0krpsztraxrvftk40ys2dde8u696h5ymphf2qjpg0df

  - path_regex: .*\.enc\.tfvars$
    age: age16v3c6ulmkwr2nav0krpsztraxrvftk40ys2dde8u696h5ymphf2qjpg0df

  # Match backend configuration files (backend.hcl -> backend.hcl.enc)
  - path_regex: backend\.hcl$
    age: age16v3c6ulmkwr2nav0krpsztraxrvftk40ys2dde8u696h5ymphf2qjpg0df

  - path_regex: backend\.enc\.hcl$
    age: age16v3c6ulmkwr2nav0krpsztraxrvftk40ys2dde8u696h5ymphf2qjpg0df
