{
 "title": "Gitea",
 "description": "Monitor Gitea server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Resident memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gitea\"}"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"gitea\"}"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"gitea\"}"
    }
   ]
  },
  {
   "title": "Number of Accesses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "expr": "gitea_accesses" }
   ]
  },
  {
   "title": "Number of Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "targets": [
    { "expr": "gitea_repositories" }
   ]
  },
  {
   "title": "Number of Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "targets": [
    { "expr": "gitea_users" }
   ]
  },
  {
   "title": "Number of Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "targets": [
    { "expr": "gitea_issues" }
   ]
  },
  {
   "title": "Number of Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "targets": [
    { "expr": "gitea_actions" }
   ]
  },
  {
   "title": "Number of Labels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "targets": [
    { "expr": "gitea_labels" }
   ]
  },
  {
   "title": "Number of Organizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "targets": [
    { "expr": "gitea_organizations" }
   ]
  },
  {
   "title": "Number of Teams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "targets": [
    { "expr": "gitea_teams" }
   ]
  },
  {
   "title": "Number of Follows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "targets": [
    { "expr": "gitea_follows" }
   ]
  },
  {
   "title": "Number of PublicKeys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "targets": [
    { "expr": "gitea_publickeys" }
   ]
  },
  {
   "title": "Number of Stars",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "targets": [
    { "expr": "gitea_stars" }
   ]
  },
  {
   "title": "Number of Webhooks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "targets": [
    { "expr": "gitea_webhooks" }
   ]
  },
  {
   "title": "Number of Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "targets": [
    { "expr": "gitea_releases" }
   ]
  },
  {
   "title": "Number of Comments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "targets": [
    { "expr": "gitea_comments" }
   ]
  },
  {
   "title": "Number of Milestones",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "targets": [
    { "expr": "gitea_milestones" }
   ]
  },
  {
   "title": "Number of Watches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "targets": [
    { "expr": "gitea_watches" }
   ]
  }
 ]
}