{
 "title": "Active Series / Chunks",
 "panels": [
  {
   "title": "Series",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"})",
     "legendFormat": "series"
    }
   ]
  },
  {
   "title": "Chunks per series",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}) / sum(loki_ingester_memory_streams{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"})",
     "legendFormat": "chunks"
    }
   ]
  }
 ]
}
{
 "title": "Flush Stats",
 "panels": [
  {
   "title": "Utilization",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_utilization_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_utilization_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_utilization_sum{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) * 1 / sum(rate(loki_ingester_chunk_utilization_count{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Age",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_age_seconds_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_age_seconds_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_age_seconds_sum{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) * 1e3 / sum(rate(loki_ingester_chunk_age_seconds_count{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "Flush Stats",
 "panels": [
  {
   "title": "Log Entries Per Chunk",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_entries_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_entries_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_entries_sum{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) * 1 / sum(rate(loki_ingester_chunk_entries_count{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Index Entries Per Chunk",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_chunk_store_index_entries_per_chunk_sum{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) / sum(rate(loki_chunk_store_index_entries_per_chunk_count{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]))",
     "legendFormat": "Index Entries"
    }
   ]
  }
 ]
}
{
 "title": "Flush Stats",
 "panels": [
  {
   "title": "Queue Length",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_ingester_flush_queue_length{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"} or cortex_ingester_flush_queue_length{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush Rate",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_ingester_chunk_age_seconds_count{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-zA-Z_]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Flush Stats",
 "panels": [
  {
   "title": "Chunks Flushed/Second",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chunk Flush Reason",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) / ignoring(reason) group_left sum(rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]))",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}
{
 "title": "Utilization",
 "panels": [
  {
   "title": "Chunk Utilization",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum by (le) (rate(loki_ingester_chunk_utilization_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Utilization",
 "panels": [
  {
   "title": "Chunk Size Bytes",
   "type": "heatmap",
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Utilization",
 "panels": [
  {
   "title": "Chunk Size Quantiles",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}
{
 "title": "Duration",
 "panels": [
  {
   "title": "Chunk Duration hours (end-start)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(loki_ingester_chunk_bounds_hours_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_bounds_hours_bucket{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_bounds_hours_sum{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval])) / sum(rate(loki_ingester_chunk_bounds_hours_count{cluster=\"$cluster\", job=~\"$namespace/loki.*-write\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}
{
 "title": "Loki / Logs",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "container",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\"}, container)"
   },
   { "name": "level", "query": "debug,info,warn,error" },
   { "name": "filter", "label": "LogQL Filter" }
  ]
 },
 "panels": [
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(go_goroutines{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"  })"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "working set",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "tx",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod)(rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) * on(namespace, pod) group_left() max by(namespace, pod) (kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "rx",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, pod)(rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) * on(namespace, pod) group_left() max by(namespace, pod) (kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "restarts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"}[30m]) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\" } |logfmt| level=~\"$level\" |= \"$filter\" | __error__=\"\" [$__auto])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"} | logfmt | level=~\"$level\" |= \"$filter\""
    }
   ]
  }
 ]
}
{
 "title": "Loki / Operational",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries/Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(loki_request_duration_seconds_count{cluster=\"$cluster\", job=~\"($namespace)/loki.*-read\", route=~\"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pushes/Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n          rate(loki_request_duration_seconds_count{cluster=\"$cluster\", job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs\"}[$__rate_interval]),\n   \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Lines Per Tenant (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_lines_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "MBs Per Tenant (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_bytes_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (tenant)) / 1024 / 1024",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\"}[10m]) > 0",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Push Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (cluster_job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (cluster_job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=\"/logproto.Pusher/Push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=\"/logproto.Pusher/Push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=\"/logproto.Pusher/Push\", cluster=~\"$cluster\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\", status_code!~\"5[0-9]{2}\", route=\"/logproto.Pusher/Push\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\", route=\"/logproto.Pusher/Push\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"}))",
     "legendFormat": "{{route}}-.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"}))",
     "legendFormat": "{{route}}-.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"}))",
     "legendFormat": "{{route}}-.5"
    }
   ]
  },
  {
   "title": "Querier Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-read\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Querier Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-read\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-read\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Read",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/loki.*-write\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", cluster=\"$cluster\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Read",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\", status_code!~\"5[0-9]{2}\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discarded Lines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum by (tenant, reason) (rate(loki_discarded_samples_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    },
    {
     "title": "Discarded Lines Per Interval",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by (tenant, reason) (sum_over_time(increase(loki_discarded_samples_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])[$__range:$__rate_interval])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"loki.*-write.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"loki.*-write.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Log Rate",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\"} | logfmt | level=\"error\"[$__auto]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\"} | logfmt | level=\"error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-write\"}[$__rate_interval])) by (route) > 0",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Append Failures By Ingester",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_append_failures_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Received/Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Lines Received/Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Streams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum by (tenant) (loki_ingester_memory_streams{cluster=\"$cluster\",job=~\"($namespace)/loki.*-write\"}))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Streams Created/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by (tenant) (rate(loki_ingester_streams_created_total{cluster=\"$cluster\",job=~\"($namespace)/loki.*-write\"}[$__rate_interval]) > 0))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunks Flushed/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\",job=~\"($namespace)/loki.*-write\"}[$__rate_interval]))",
       "legendFormat": "Chunks"
      },
      {
       "expr": "sum(increase(loki_chunk_store_deduped_chunks_total{cluster=\"$cluster\", job=~\"($namespace)/loki.*-write\"}[$__rate_interval]))/sum(increase(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", job=~\"($namespace)/loki.*-write\"}[$__rate_interval])) < 1",
       "legendFormat": "De-Dupe Ratio"
      }
     ]
    },
    {
     "title": "Chunk Size Bytes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_size_bytes_bucket{cluster=\"$cluster\",job=~\"($namespace)/loki.*-write\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Chunk Flush Reason %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(reason) (rate(loki_ingester_chunks_flushed_total{cluster=~\"$cluster\",job=~\"($namespace)/loki.*-write\", namespace=~\"$namespace\"}[$__rate_interval])) / ignoring(reason) group_left sum(rate(loki_ingester_chunks_flushed_total{cluster=~\"$cluster\",job=~\"($namespace)/loki.*-write\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Chunk Utilization",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by (le) (rate(loki_ingester_chunk_utilization_bucket{cluster=\"$cluster\", job=~\"($namespace)/loki.*-write\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"loki.*-read.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"loki.*-read.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Log Rate",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 18, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-read\"} | logfmt |  level=\"error\"[$__auto]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 18, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-read\"} | logfmt | level=\"error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-read\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-read\"}[$__rate_interval])) by (route) > 0",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"loki.*-read.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"loki.*-backend.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Log Rate",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 18, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-backend\"} | logfmt |  level=\"error\"[$__auto]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 18, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-backend\"} | logfmt | level=\"error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-backend\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"($namespace)/loki.*-backend\"}[$__rate_interval])) by (route) > 0",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_s3_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Read Path",
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/loki.*-read\", route=~\"(api_prom_rules|api_prom_rules_namespace_groupname|api_v1_rules|loki_api_v1_delete|loki_api_v1_detected_labels|loki_api_v1_index_stats|loki_api_v1_index_volume|loki_api_v1_index_volume_range|loki_api_v1_label_name_values|loki_api_v1_label_values|loki_api_v1_labels|loki_api_v1_patterns|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_series|prometheus_api_v1_rules)\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-zA-Z_]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-read\", route=~\"(api_prom_rules|api_prom_rules_namespace_groupname|api_v1_rules|loki_api_v1_delete|loki_api_v1_detected_labels|loki_api_v1_index_stats|loki_api_v1_index_volume|loki_api_v1_index_volume_range|loki_api_v1_label_name_values|loki_api_v1_label_values|loki_api_v1_labels|loki_api_v1_patterns|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_series|prometheus_api_v1_rules)\"})) * 1e3",
     "legendFormat": "{{ route }} 99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-read\", route=~\"(api_prom_rules|api_prom_rules_namespace_groupname|api_v1_rules|loki_api_v1_delete|loki_api_v1_detected_labels|loki_api_v1_index_stats|loki_api_v1_index_volume|loki_api_v1_index_volume_range|loki_api_v1_label_name_values|loki_api_v1_label_values|loki_api_v1_labels|loki_api_v1_patterns|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_series|prometheus_api_v1_rules)\"})) * 1e3",
     "legendFormat": "{{ route }} 50th percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job_route:loki_request_duration_seconds_sum:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-read\", route=~\"(api_prom_rules|api_prom_rules_namespace_groupname|api_v1_rules|loki_api_v1_delete|loki_api_v1_detected_labels|loki_api_v1_index_stats|loki_api_v1_index_volume|loki_api_v1_index_volume_range|loki_api_v1_label_name_values|loki_api_v1_label_values|loki_api_v1_labels|loki_api_v1_patterns|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_series|prometheus_api_v1_rules)\"}) by (route)  / sum(cluster_job_route:loki_request_duration_seconds_count:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-read\", route=~\"(api_prom_rules|api_prom_rules_namespace_groupname|api_v1_rules|loki_api_v1_delete|loki_api_v1_detected_labels|loki_api_v1_index_stats|loki_api_v1_index_volume|loki_api_v1_index_volume_range|loki_api_v1_label_name_values|loki_api_v1_label_values|loki_api_v1_labels|loki_api_v1_patterns|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_series|prometheus_api_v1_rules)\"}) by (route) ",
     "legendFormat": "{{ route }} Average"
    }
   ]
  },
  {
   "title": "Per Pod Latency (p99)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-read\", route=~\"(api_prom_rules|api_prom_rules_namespace_groupname|api_v1_rules|loki_api_v1_delete|loki_api_v1_detected_labels|loki_api_v1_index_stats|loki_api_v1_index_volume|loki_api_v1_index_volume_range|loki_api_v1_label_name_values|loki_api_v1_label_values|loki_api_v1_labels|loki_api_v1_patterns|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_series|prometheus_api_v1_rules)\"}[$__rate_interval])) by (le,pod)) * 1e3",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Read path",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-read\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Write path",
 "panels": [
  {
   "title": "In-memory streams",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (loki_ingester_memory_streams{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-write\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-write\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "panels": [
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node, device) (rate(node_disk_written_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(node, pod, device) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node, device) (rate(node_disk_read_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(node, pod, device) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-write.*\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  }
 ]
}
{
 "title": "Backend path",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-backend\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "panels": [
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node, device) (rate(node_disk_written_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(node, pod, device) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node, device) (rate(node_disk_read_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(node, pod, device) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-backend.*\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  }
 ]
}
{
 "title": "Resource Usage",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"loki\", pod=~\"loki.*-read.*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-backend\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Compaction",
 "panels": [
  {
   "title": "Last Compact Tables Operation Success",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_last_successful_run_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"} * 1e3"
    }
   ]
  },
  {
   "title": "Compact Tables Operations Duration",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "duration"
    }
   ]
  }
 ]
}
{
 "panels": [
  {
   "title": "Number of times Tables were skipped during Compaction",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(loki_compactor_locked_table_successive_compaction_skips{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Compact Tables Operations Per Status",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_compact_tables_operation_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{success}}"
    }
   ]
  }
 ]
}
{
 "title": "Retention",
 "panels": [
  {
   "title": "Last Mark Operation Success",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_compactor_apply_retention_last_successful_run_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"} * 1e3"
    }
   ]
  },
  {
   "title": "Mark Operations Duration",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_compactor_apply_retention_operation_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Mark Operations Per Status",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_compactor_apply_retention_operation_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{success}}"
    }
   ]
  }
 ]
}
{
 "title": "Per Table Marker",
 "panels": [
  {
   "title": "Processed Tables Per Action",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(action)(loki_boltdb_shipper_retention_marker_table_processed_total{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Modified Tables",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(table,action)(loki_boltdb_shipper_retention_marker_table_processed_total{cluster=~\"$cluster\", namespace=~\"$namespace\" , action=~\"modified|deleted\"})",
     "legendFormat": "{{table}}-{{action}}"
    }
   ]
  },
  {
   "title": "Marks Creation Rate Per Table",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (table)(rate(loki_boltdb_shipper_retention_marker_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) >0",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}
{
 "panels": [
  {
   "title": "Marked Chunks (24h)",
   "type": "singlestat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "targets": [
    {
     "expr": "sum (increase(loki_boltdb_shipper_retention_marker_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Mark Table Latency",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "Sweeper",
 "panels": [
  {
   "title": "Delete Chunks (24h)",
   "type": "singlestat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "targets": [
    {
     "expr": "sum (increase(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Delete Latency",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "panels": [
  {
   "title": "Sweeper Lag",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (loki_boltdb_shipper_retention_sweeper_marker_file_processing_current_time{cluster=~\"$cluster\", namespace=~\"$namespace\"} > 0)",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Marks Files to Process",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(loki_boltdb_shipper_retention_sweeper_marker_files_current{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Delete Rate Per Status",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Logs",
 "panels": [
  {
   "title": "Compactor Logs",
   "type": "logs",
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-backend\"}"
    }
   ]
  }
 ]
}
{
 "title": "Write Path",
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{cluster=~\"$cluster\",job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-zA-Z_]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"})) * 1e3",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"})) * 1e3",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job_route:loki_request_duration_seconds_sum:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"}) / sum(cluster_job_route:loki_request_duration_seconds_count:sum_rate{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Per Pod Latency (p99)",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket{cluster=~\"$cluster\", job=~\"($namespace)/loki.*-write\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"}[$__rate_interval])) by (le,pod)) * 1e3",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Write Path - Structured Metadata",
 "panels": [
  {
   "title": "Per Total Received Bytes",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(loki_distributor_structured_metadata_bytes_received_total{cluster=~\"$cluster\",job=~\"($namespace)/loki.*-write\",}[$__rate_interval])) / sum(rate(loki_distributor_bytes_received_total{cluster=~\"$cluster\",job=~\"($namespace)/loki.*-write\",}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Per Tenant",
   "type": "timeseries",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_structured_metadata_bytes_received_total{cluster=~\"$cluster\",job=~\"($namespace)/loki.*-write\",}[$__rate_interval])) / ignoring(tenant) group_left sum(rate(loki_distributor_structured_metadata_bytes_received_total{cluster=~\"$cluster\",job=~\"($namespace)/loki.*-write\",}[$__rate_interval]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  }
 ]
}