# Local SOPS configuration for gitops-shangkuei-dev environment
# This allows running SOPS commands from within this directory
#
# IMPORTANT: Replace the age public key below with your own key.
# Generate a new key with: make age-keygen
# The public key will be displayed after generation.
creation_rules:
  # Match input files for encryption (terraform.tfvars -> terraform.tfvars.enc)
  - path_regex: .*\.tfvars$
    age: age1vjnzfu8s5vxwskhq5s2y3c9lgwk73r77xflzum5ruck8se6frp6qrkxkav

  - path_regex: .*\.tfvars\.enc$
    age: age1vjnzfu8s5vxwskhq5s2y3c9lgwk73r77xflzum5ruck8se6frp6qrkxkav

  # Match backend configuration files (backend.hcl -> backend.hcl.enc)
  - path_regex: backend\.hcl$
    age: age1vjnzfu8s5vxwskhq5s2y3c9lgwk73r77xflzum5ruck8se6frp6qrkxkav

  - path_regex: backend\.hcl\.enc$
    age: age1vjnzfu8s5vxwskhq5s2y3c9lgwk73r77xflzum5ruck8se6frp6qrkxkav
