---
# Cloudflared DaemonSet
# Runs cloudflared on every node for tunnel connectivity
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared
  namespace: edatw
  labels:
    app: cloudflared
    app.kubernetes.io/name: edatw
    app.kubernetes.io/component: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cloudflared
        app.kubernetes.io/name: edatw
        app.kubernetes.io/component: cloudflared
    spec:
      serviceAccountName: cloudflared
      hostNetwork: false
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          imagePullPolicy: IfNotPresent
          args:
            - tunnel
            - --no-autoupdate
            - --protocol
            - http2
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-credentials
                  key: tunnel-token
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 50m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          livenessProbe:
            httpGet:
              path: /metrics
              port: 20241
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: 20241
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
