# ArgoCD SOPS Age key secret (to be encrypted)
# This secret is deployed to argocd namespace for KSOPS decryption
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: argocd
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:m94IDBJfZ13sjQ8ltgarEhWyy/mbk82Dbi7/7Ppm2/hhqQO9CyFvdwEUOHPQCMpQxNGUnRrhJalxTPk5nG9y7ceeKp07oQP5yvaPtDqGWJQj9pxDfWXznY9OTtOrqI+qktc5ljSkhTJc1gaApQ/cbbTdUNebkaUCas27vcFTTHYHeg6vnH4gp/GMBpm6dxHKedQ4W19GYKOMwUKdVIsJOAndLSnp92SUUh8SrkizmjUdhvSHvhEwLfDOATXY,iv:4lQ0PxV0/sxWVdVjvX9Xx3o5rbXVePQpFzWoKW9CiaE=,tag:6QW86y4sSFc45R54+s4Amw==,type:str]
sops:
    age:
        - recipient: age1xd9vrcj6n5nazq3tek8t89qxaky5eg9339phyddeemu99hqgvfcqkr2ysp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TmJRT2V0VkVFRVJEOVNs
            WW5oUHZMQ0VVUUVZMEFHMHhDendQWkhyckFRCmxYNkhYUWRBUmlPR0ZFbkFxYnZJ
            Rms3QnNEejlzbUJKcWMrN0NFeFl3RmMKLS0tIGt2V3NQSHZPUEpEcGFhMnplUE9n
            NnFFS2Jydjc5TTVDQUJGdmoxdldQK0kKzY4Pl6jmYr+REjHDt4hIVh94BhWhT90u
            9cGLplQ0UnxAz4etsaWCfbIYt322i3PnITv3+TLSs+o0malYuIgbhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:08:30Z"
    mac: ENC[AES256_GCM,data:eSzSyJlzo59urA/UuBwsnsjaiFiuzo9gix7vayYycDKCBHT3FMfEuy34gl0YfWqDkKch6xJwTTVUEbYpEYHsXXcsfy8WLuWdA5N4ZM6mPN+/7uEWLf7PN7MiMSUf3dCg/T6/23bwIiXxXNT1HKU2UBK1m3Qb61oVu85KrraPO4M=,iv:8rIBxfPjqGz9+OAfyp684LZB4X7/p72HHH2R0ckKhbU=,tag:VxRz2sLdmKxd5GZIwPmTEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
